### ISSUE TITLE
NOTICE: Codesensor Tool Working Capacity

### ISSUE THREAD

**Issue by qtl1106** [arpit2412/g8-serp2021#11]
From the current experiment experience, the Codesensor Tool cannot handle a large number of files when extracting the AST from the source code.
Our working environment is 16GB RAM.
If there are over 2000 function files in the source functions directory, the codesensor will quickly occupy the memory. When the memory is full, it will cause system lags / no responding for a while and might accidentally shut down the machine.
The issue raises when there are too many files that need to be processed in the directory.
Our current recommendation is that depends on the RAM of your PC, please put a lesser number of files in the source file directory and manually repeat several times to process all files.

**Comment by zhangfanfansz** [comment]
6000 functions sample is good in my pc
