### ISSUE TITLE
RandomForest.py issues with data input "NaN"

### ISSUE THREAD

**Issue by qtl1106** [arpit2412/g8-serp2021#12]
When the RandomForest.py get the data from the numerical vector, the empty space will be recognized as "NaN" which it should be filled with "0" in those spaces.
The current idea is using the same Padding functions in the LSTM.py and limited the length to 650 and fill the spaces with "0"

**Comment by zhangfanfansz** [comment]
![image](https://user-images.githubusercontent.com/58411513/120641749-255d6580-c4b3-11eb-8310-9b66ec8656b4.png)
we can use this piece of code to handle this issue

**Comment by qtl1106** [comment]
Issue solved.
