### ISSUE TITLE
Abnormal Prediction result of Random Forest Method

### ISSUE THREAD

**Issue by qtl1106** [arpit2412/g8-serp2021#14]
The Random Forest method generated abnormal results which are significantly higher than the paper’s result.
After repeat several times RandomForest.py, the results remaining unchanged and significantly higher than the paper result even higher than LSTM. 
The issue needs to be evaluated to identify that it is our replicating process wrong or the paper provided an invalid result.

**Comment by zhangfanfansz** [comment]
We might wrongly extract the AST from the data, as the paper says, we need to extract the essential complexity of these codes. I assume they are the code matrix from the commercial tool "understand".

**Comment by qtl1106** [comment]
Thanks for clarifying that. Close the issue with merge request
