### ISSUE TITLE
POSTER paper methods need to be verified with other dataset

### ISSUE THREAD

**Issue by qtl1106** [arpit2412/g8-serp2021#17]
The POSTER paper's methods have been verified with author provided dataset. Our second attempt has similar result compare with the paper. This can be demonstrated by our result curve has a similar pattern with the paper provided. 
The similar results of LSTM and RF could support the credibility of the paper method. Therefore, our conclusion of the current stage is that the paper has provided a valid dataset and valid vulnerability detection methods.

Our next step is to validate the paper methods and results by using other datasets.

**Comment by zhangfanfansz** [comment]
I have found another paper with "Sysevr" at start, and I believe we can directly use the data of it to validate our result
