### ISSUE TITLE
Can't train a accurate model by dan.py

### ISSUE THREAD

**Issue by zhangfanfansz** [arpit2412/g8-serp2021#25]
After repeating the process mentioned by the paper, we add a model save function into the dan.py and pick the best model from the 8 different parameter combinations, however, when predicting the model by dan_predict, it gives out a wrong result. Then I tried to use the trained model from the author and it worked well.

**Comment by qtl1106** [comment]
As we discussed with the Client, our first target find out it is our problem or the author's code problem.
Suggestions:
1. reduce parameters to reduce training time to test
2. Instead of saving the model then use, directly use the trained model
3. if still can't find out the problems, ask author

**Comment by zhangfanfansz** [comment]
Good news. we have fixed this issue by correcting the timing for storing the model. We should store the model only when the f1 score has been updated.

**Comment by zhangfanfansz** [comment]
issue fixed
